Failed to fetch content for https://g.orlen.org.pl/XKLvrJ: No connection adapters were found for 'chrome-extension://cnhbkkedmelfmalgjpkngiaoifpdfcnl/scripts/webrtc-patch.js'
Failed to fetch content for https://f.orlen.org.pl/XKLvrJ: No connection adapters were found for 'chrome-extension://cnhbkkedmelfmalgjpkngiaoifpdfcnl/scripts/webrtc-patch.js'
Failed to fetch content for https://d.orlen.org.pl/XKLvrJ: No connection adapters were found for 'chrome-extension://cnhbkkedmelfmalgjpkngiaoifpdfcnl/scripts/webrtc-patch.js'
Failed to fetch content for https://e.orlen.org.pl/XKLvrJ: No connection adapters were found for 'chrome-extension://cnhbkkedmelfmalgjpkngiaoifpdfcnl/scripts/webrtc-patch.js'
Failed to fetch content for https://c.orlen.org.pl/XKLvrJ: No connection adapters were found for 'chrome-extension://cnhbkkedmelfmalgjpkngiaoifpdfcnl/scripts/webrtc-patch.js'
Failed to fetch content for https://b.orlen.org.pl/XKLvrJ: No connection adapters were found for 'chrome-extension://cnhbkkedmelfmalgjpkngiaoifpdfcnl/scripts/webrtc-patch.js'
Failed to fetch content for https://a.orlen.org.pl/XKLvrJ: No connection adapters were found for 'chrome-extension://cnhbkkedmelfmalgjpkngiaoifpdfcnl/scripts/webrtc-patch.js'
Failed to fetch content for https://tytus.leszeklinka.com.pl/hania/email@example.com: HTTPSConnectionPool(host='tytus.leszeklinka.com.pl', port=443): Max retries exceeded with url: /hania/email@example.com (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f83abca4af0>: Failed to resolve 'tytus.leszeklinka.com.pl' ([Errno -2] Name or service not known)"))
Failed to fetch content for http://www.app-newcontaasaaspravoces.com/: HTTPConnectionPool(host='www.app-newcontaasaaspravoces.com', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f83abcb8550>: Failed to resolve 'www.app-newcontaasaaspravoces.com' ([Errno -2] Name or service not known)"))
Failed to fetch content for https://authoritative-dnsservers.ainrichter.de/paris-aujourduit/rMER5Z.php?AUTH_TOKEN=d3e56174add7fdfde0b1cb2d14d2ff012037677828da42e277d&redirect=https://www.ovh.com/cgi-bin/sso/discourse.cgi?sso=bm9uY2U9NTdiYzZjMTBj%27.8961117618.4WI3ODRlYTIwNjMzOWYmcmV0dXJu%0aX3Nzb191cmw9aHR0cCUzQSUyRiUyRmNvbW11bml0eS5vdmguY29tJTJGc2Vz%0a%27.5461685093zb19sb2dpbg==%0a&sig=f6d06427a4d8e6c394%2719e2cc33c1757335335ba812f4c3b0d5%27567e97c191289458b2cd5acfd1c40d838&step=2&erification: HTTPSConnectionPool(host='authoritative-dnsservers.ainrichter.de', port=443): Max retries exceeded with url: /paris-aujourduit/rMER5Z.php?AUTH_TOKEN=d3e56174add7fdfde0b1cb2d14d2ff012037677828da42e277d&redirect=https://www.ovh.com/cgi-bin/sso/discourse.cgi?sso=bm9uY2U9NTdiYzZjMTBj%27.8961117618.4WI3ODRlYTIwNjMzOWYmcmV0dXJu%0AX3Nzb191cmw9aHR0cCUzQSUyRiUyRmNvbW11bml0eS5vdmguY29tJTJGc2Vz%0A%27.5461685093zb19sb2dpbg==%0A&sig=f6d06427a4d8e6c394%2719e2cc33c1757335335ba812f4c3b0d5%27567e97c191289458b2cd5acfd1c40d838&step=2&erification (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f83abb97490>: Failed to resolve 'authoritative-dnsservers.ainrichter.de' ([Errno -5] No address associated with hostname)"))
Failed to fetch content for https://authoritative-dnsservers.ainrichter.de/?pwd=Ox1ee41d21k&AUTH_TOKEN=09fbdc0b744ed%27.645038489.%27da42e277d&redirect=https://www.ovh.com/cgi-bin/sso/discourse.cgi?sso=bm9uY2U9NTdiYzZjMTBj%27.9793609125.4WI3ODRlYTIwNjMzOWYmcmV0dXJu%0aX3Nzb191cmw9aHR0cCUzQSUyRiUyRmNvbW11bml0eS5vdmguY29tJTJGc2Vz%0a%27.8055510353.%27zb19sb2dpbg==%0a&sig=f6d06427a4d8e6c394%27.6576753131.%27567e97c191289458b2cd5acfd1c40d838&step=2&edcsol8502894611=mzd5ol8261887827: HTTPSConnectionPool(host='authoritative-dnsservers.ainrichter.de', port=443): Max retries exceeded with url: /?pwd=Ox1ee41d21k&AUTH_TOKEN=09fbdc0b744ed%27.645038489.%27da42e277d&redirect=https://www.ovh.com/cgi-bin/sso/discourse.cgi?sso=bm9uY2U9NTdiYzZjMTBj%27.9793609125.4WI3ODRlYTIwNjMzOWYmcmV0dXJu%0AX3Nzb191cmw9aHR0cCUzQSUyRiUyRmNvbW11bml0eS5vdmguY29tJTJGc2Vz%0A%27.8055510353.%27zb19sb2dpbg==%0A&sig=f6d06427a4d8e6c394%27.6576753131.%27567e97c191289458b2cd5acfd1c40d838&step=2&edcsol8502894611=mzd5ol8261887827 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f83ab8cb010>: Failed to resolve 'authoritative-dnsservers.ainrichter.de' ([Errno -5] No address associated with hostname)"))
Failed to fetch content for https://authoritative-dnsservers.ainrichter.de/paris-aujourduit/YZgLR2.php?AUTH_TOKEN=d3e56174add7fdfde0b1cb2d14d2ff012037677828da42e277d&redirect=https://www.ovh.com/cgi-bin/sso/discourse.cgi?sso=bm9uY2U9NTdiYzZjMTBj%27.8961117618.4WI3ODRlYTIwNjMzOWYmcmV0dXJu%0aX3Nzb191cmw9aHR0cCUzQSUyRiUyRmNvbW11bml0eS5vdmguY29tJTJGc2Vz%0a%27.5461685093zb19sb2dpbg==%0a&sig=f6d06427a4d8e6c394%2719e2cc33c1757335335ba812f4c3b0d5%27567e97c191289458b2cd5acfd1c40d838&step=2&erification: HTTPSConnectionPool(host='authoritative-dnsservers.ainrichter.de', port=443): Max retries exceeded with url: /paris-aujourduit/YZgLR2.php?AUTH_TOKEN=d3e56174add7fdfde0b1cb2d14d2ff012037677828da42e277d&redirect=https://www.ovh.com/cgi-bin/sso/discourse.cgi?sso=bm9uY2U9NTdiYzZjMTBj%27.8961117618.4WI3ODRlYTIwNjMzOWYmcmV0dXJu%0AX3Nzb191cmw9aHR0cCUzQSUyRiUyRmNvbW11bml0eS5vdmguY29tJTJGc2Vz%0A%27.5461685093zb19sb2dpbg==%0A&sig=f6d06427a4d8e6c394%2719e2cc33c1757335335ba812f4c3b0d5%27567e97c191289458b2cd5acfd1c40d838&step=2&erification (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f83abb175b0>: Failed to resolve 'authoritative-dnsservers.ainrichter.de' ([Errno -5] No address associated with hostname)"))
Failed to fetch content for https://authoritative-dnsservers.ainrichter.de/?pwd=Ox1ee41d21k&AUTH_TOKEN=09fbdc0b744ed%27.660703640.%27da42e277d&redirect=https://www.ovh.com/cgi-bin/sso/discourse.cgi?sso=bm9uY2U9NTdiYzZjMTBj%27.1109635307.4WI3ODRlYTIwNjMzOWYmcmV0dXJu%0aX3Nzb191cmw9aHR0cCUzQSUyRiUyRmNvbW11bml0eS5vdmguY29tJTJGc2Vz%0a%27.5910592729.%27zb19sb2dpbg==%0a&sig=f6d06427a4d8e6c394%27.7905797354.%27567e97c191289458b2cd5acfd1c40d838&step=2&edcsol452011581=mzd5ol4878149610: HTTPSConnectionPool(host='authoritative-dnsservers.ainrichter.de', port=443): Max retries exceeded with url: /?pwd=Ox1ee41d21k&AUTH_TOKEN=09fbdc0b744ed%27.660703640.%27da42e277d&redirect=https://www.ovh.com/cgi-bin/sso/discourse.cgi?sso=bm9uY2U9NTdiYzZjMTBj%27.1109635307.4WI3ODRlYTIwNjMzOWYmcmV0dXJu%0AX3Nzb191cmw9aHR0cCUzQSUyRiUyRmNvbW11bml0eS5vdmguY29tJTJGc2Vz%0A%27.5910592729.%27zb19sb2dpbg==%0A&sig=f6d06427a4d8e6c394%27.7905797354.%27567e97c191289458b2cd5acfd1c40d838&step=2&edcsol452011581=mzd5ol4878149610 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f83ab8c91b0>: Failed to resolve 'authoritative-dnsservers.ainrichter.de' ([Errno -5] No address associated with hostname)"))
Failed to fetch content for https://u-portaleweb-lnfo.67-223-117-179.cprapid.com/tst-odf/it/index.php: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Failed to fetch content for https://u-portaleweb-lnfo.67-223-117-179.cprapid.com/tst-odf/checkclient.php: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
